#!/usr/bin/env bash

#export HBNB_MYSQL_USER = os.environ.get('HBNB_MYSQL_USER', 'hbnb_dev')
#export HBNB_MYSQL_PWD = os.environ.get('HBNB_MYSQL_PWD', 'hbnb_dev_pwd')
#export HBNB_MYSQL_HOST = os.environ.get('HBNB_MYSQL_HOST', 'localhost')
#export HBNB_MYSQL_DB = os.environ.get('HBNB_MYSQL_DB', 'hbnb_dev_db')
#export HBNB_TYPE_STORAGE = os.environ.get('HBNB_TYPE_STORAGE', 's')
#export HBNB_ENV = os.environ.get('HBNB_ENV')

export alias_name='Moses'
